# Generated by Django 4.2.4 on 2023-09-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("year", models.IntegerField()),
                ("genres", models.CharField(max_length=200)),
            ],
        ),
    ]
